### ISSUE TITLE
CF dev panic

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry-incubator/cfdev#30]
Running the latest CF CLI v.6.36.1 and 6.36.2, `cf dev` panics , i.e. no help text.  I can use `cf dev start` as expected, but figured looking for help text might be a common first action.

```
$ cf install-plugin http://d3p1cc0zb2wjno.cloudfront.net/cfdev/cfdev-v0.0.4-darwin
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin http://d3p1cc0zb2wjno.cloudfront.net/cfdev/cfdev-v0.0.4-darwin? [yN]: y
Starting download of plugin binary from URL...
 8.78 MiB / 8.78 MiB [=================================================================================] 100.00% 2s
Installing plugin cfdev...
OK
Plugin cfdev 0.0.4 successfully installed.
xenophon:github stuartcharlton$ cf dev
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*Plugin).Run(0xc4201f40f0, 0x4532400, 0xc42014c660, 0xc42001e1d0, 0x1, 0x1)
	/ext-go/1/src/code.cloudfoundry.org/cfdev/main.go:106 +0x40f
code.cloudfoundry.org/cli/plugin.Start(0x452a080, 0xc4201f40f0)
	/ext-go/1/src/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x2a0
main.main()
	/ext-go/1/src/code.cloudfoundry.org/cfdev/main.go:81 +0x8db
xenophon:github stuartcharlton$ cf -v
cf version 6.36.1+e3799ad7e.2018-04-04

```

**Comment by ssherwood** [comment]
Seeing this as well on the latest version (on Mac):

➜  ~ cf -v
cf version 6.37.0+a40009753.2018-05-25

➜  ~ cf dev version
Version: 0.0.6

**Comment by sclevine** [comment]
Thanks for the pointer! This should probably be a synonym for `cf dev help`, but that's currently not implemented.

**Comment by dgodd** [comment]
@sclevine I believe the commit above fixes this

**Comment by aemengo** [comment]
This issue has been resolved, versions ago. Closing...
